'use client'
import React, {useContext } from 'react';
import VerticalNavBar from './components/VerticalNavBar';
import NavBar from '../../components/NavBar/NavBar';
import { MobileContext, MobileProvider } from '../context/mobileContext';
import '../globals.css'

export const metadata = {
  title: 'LAB Admin DashBoard',
  description: 'Generated by create next app',
}

export default function AdminLayout({ children }) {
    const {isMobile} = useContext(MobileContext);

    const NavContent = [
        ['Home','/'],['Dashboard','/admin/dashboard'], ['Application','/admin/application'],['Project','/admin/project' ]
    ]
  return (
    <MobileProvider>
      <main className='bg-custom-blur-white dark:bg-custom-black w-full  font-Inter relative min-h-screen overflow-y-hidden'>
            {isMobile ? (
                <section className=' text-white  pb-8 '>
                    <div className='w-full flex flex-col gap-8 items-center justify-center  '>
                        <NavBar props={NavContent} ColorBackground={"#13F287"} ColorText={"#040406"} MobileColorBackground={"#040406"} MobileColorText={"#13F287"} />
                        <div className='w-full px-[8%] overflow-y-scroll'>
                        {children}
                        </div>
                    </div>
                </section>
            ) :(
                <section className='w-full flex flex-row text-white  relative font-Inter max-h-screen'>
                    <VerticalNavBar props={NavContent} />
                    {/*--------------------------------------------------*/}
                    <div className='w-full bg-custom-blur-white dark:bg-custom-black flex flex-col gap-8 item-center px-[5%] overflow-y-auto py-8'>
                        {/*--------------------------------------------------*/}
                        <div className='w-full '>
                            {children}
                        </div>                 
                    </div>             
                </section>
            )}
        </main>
    </MobileProvider>    
  )
}
