import './globals.css'
import { MobileProvider } from './context/mobileContext';

export const metadata = {
  title: 'LAB Summer Intern',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <MobileProvider> 
          {children}
        </MobileProvider>
      </body>
    </html>
  )
}
