'use client'
import React, { useContext } from 'react';
import { MobileProvider ,MobileContext } from '../context/mobileContext'
import '../globals.css'
import VerticalNavBar from '../../components/NavBar/VerticalNavBar';
import NavBar from '../../components/NavBar/NavBar';

export const metadata = {
  title: 'LAB Student DashBoard',
  description: 'Generated by create next app',
}

export default function StudentLayout({ children }) {
  const {isMobile} = useContext(MobileContext);
    
    const NavContent = [
        ['Home','/'],['Dashboard','/student/dashboard'], ['Project','/student/project'] , ['Certificate','/student/certificate']
    ]

  return (
    <MobileProvider>
      <main className='bg-custom-black w-full  font-Inter relative'>
            {isMobile ? (
                <section className=' text-white  pb-8 '>
                    <div className='w-full flex flex-col gap-8 items-center justify-center  '>
                        <NavBar props={NavContent} ColorBackground={"#13F287"} ColorText={"#040406"} MobileColorBackground={"#040406"} MobileColorText={"#13F287"} />
                        <div className='w-full px-[8%] overflow-y-scroll'>
                          {children}
                        </div>
                    </div>
                </section>
            ) :(
                <section className='w-full  flex flex-row text-white  relative font-Inter max-h-screen'>
                    <VerticalNavBar props={NavContent} />
                    {/*--------------------------------------------------*/}
                    <div className='w-full bg-custom-dim-black flex flex-col gap-8 item-center px-[5%]  overflow-y-auto py-8'>
                        {/*--------------------------------------------------*/}
                        <div className='w-full ' id='main-dashboard'>
                            {children}
                        </div>                 
                    </div>             
                </section>
            )}
        </main>
    </MobileProvider>    
  )
}
